/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.graph.GraphBuilder;
import com.google.common.graph.MutableGraph;
import java.util.Random;

@SuppressWarnings("java:S106")
public class HelloOtus {
    public static void main(String... args) {
        int min = 0;
        int max = 9;
        Random rnd = new Random();
        GraphBuilder<Object> graphBuilder = GraphBuilder.directed();
        graphBuilder.allowsSelfLoops(true);
        MutableGraph<Integer> graph = graphBuilder.build();
        for (int nodeU = min; nodeU < max; nodeU++) {
            Integer nodeV = rnd.nextInt(min, max + 1);
            graph.addNode(nodeU);
            graph.addNode(nodeV);
            graph.putEdge(nodeU, nodeV);
        }
        System.out.println("Graph: " + graph.toString());
    }
}
