spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/orchestrator
    username: usr
    password: pwd
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080
  servlet:
    contextPath: /orchestrator